---
title: "z-sanity-checks-kasper"
author: "WM"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=TRUE,echo=FALSE}
# Global chunk options
knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "center",
	fig.height = 5,
	fig.width = 10,
	message = FALSE,
	warning = FALSE
)
if(!require("pacman")) install.packages("pacman")
pacman::p_load(readxl, tidyverse, cowplot,Hmisc,ggcorrplot,usdm)

```

```{r helper-functions,include=TRUE}
# HELPER FUNCTIONS  -------------------------------------------------------
merge_by_rownames <- function(x,y) {
  merge <- merge(x,y,by='row.names')
  rownames(merge) <- merge$Row.names
  merge[,!colnames(merge) %in% c('Row.names')]
}
# MAKING DFs FUNCTIONS  ----------------------------------------------------
make_master_df <- function(dir,pattern){
  pattern2match <- pattern
  
  matching_folders <- list.dirs(dir, recursive = FALSE, full.names = F)
  matching_folders <- matching_folders[grepl(pattern2match,
                                             basename(matching_folders))]
  model <- matching_folders[1]
  models_nums <- as.numeric(str_extract(matching_folders, "(?<=Atlas)\\d+"))
  
  outputs <- lapply(matching_folders,function(model){
    # read objects
    MF <- readRDS(file.path(dir,
                            model,
                            'Results',
                            sprintf('%sMF.rds',
                                    model)))
    VP <- readRDS(file.path(dir,
                            model,
                            'Results',
                            sprintf('%sVP.rds',
                                    model)))
    load(file.path(dir,
                   model,
                   'Models/Fitted',
                   sprintf('HPC_samples_0250_thin_100_chains_4.Rdata')))
    m <- fitted_model$posteriors
    return(m)
  })
  names(outputs) <- models_nums
  # get enviro data
  Xs <- lapply(outputs, function(df) df$XData)
  Ys <- lapply(outputs, function(df) df$Y)
  Designs <- lapply(outputs, function(df) df$studyDesign)
  ranLevels <- lapply(outputs, function(df) df$ranLevels)
  s <- lapply(ranLevels, function(df) df$s)
  i<-1
  merged_list <- lapply(seq_along(outputs), function(i) {
    
    # Get the pieces for this specific model
    X_df <- as.data.frame(Xs[[i]])
    Y_df <- as.data.frame(Ys[[i]])
    Des  <- as.data.frame(Designs[[i]])
    ses <- as.data.frame(s[[i]]$s)
    
    head(X_df[,1:5])
    head(Y_df[,1:5])
    head(Des)
    head(ses)
    # Merge them together
    # We use '0' to merge by rownames in base R
    
    # 1. Merge the Sample-level data (X, Y, and Design)
    # merge(..., by = 0) merges by row names
    combined_samples <- merge(X_df, Y_df, by = 0) %>%
      column_to_rownames("Row.names") %>%
      merge(Des, by = 0) %>%
      column_to_rownames("Row.names")
    
    # 2. Add the Spatial data (ses)
    # Since 'ses' uses site names as rownames, we merge it with the 'site' column 
    # we just got from 'Des'
    final_df <- combined_samples %>%
      rownames_to_column("sample_id") %>%
      # Merge with ses: by.x is our column 'site', by.y is rownames of 'ses'
      merge(ses, by.x = "site", by.y = 0, all.x = TRUE) %>%
      # Put the sample ID back as the rowname
      column_to_rownames("sample_id")
    
    # 3. Clean up (Optional)
    # If you have an "(Intercept)" column from X_df that you don't need:
    final_df <- final_df %>% select(-any_of("(Intercept)"))%>%
      mutate(atlas = sapply(strsplit(rownames(.), "_"), "[", 2)) %>%
      
      # 3. REORDER: Move metadata to the front
      relocate(site, atlas, X, Y) 
    
    head(final_df)
    
    return(final_df)
  })
  
  # 4. Collapse the list into one large Master Dataframe
  master_df <- bind_rows(merged_list) %>%
    # Optional: Convert atlas to a factor for better plotting later
    mutate(atlas = factor(atlas, levels = c("1", "2", "3")))
  
}
```

```{r check-corrs-environment}
df <- make_master_df(dir='./HmscOutputs',
               pattern='2026-02-10') %>%
  select(tmean_year,prec_year,hh,starts_with('perc_'))

cor_results <- rcorr(as.matrix(df), type = "spearman")

# 4. Extract the pieces
cor_matrix <- cor_results$r
p_matrix <- cor_results$P

# 5. Create the Visualization
ggcorrplot(cor_matrix, 
           hc.order = TRUE,         # Reorders variables by similarity
           type = "lower",          # Only show the bottom triangle
           lab = TRUE,              # Show the numbers on the plot
           p.mat = p_matrix,        # Uses the p-values for significance
           insig = "blank",         # Hides non-significant correlations
           colors = c("#E46726", "white", "#6D9EC1"), # DarkRed to Blue
           title = "Correlation Matrix of Environmental Variables")

vifstep(df_numeric)

landuse <- df %>% 
  select(hh,starts_with('perc_'))

m <- lm(hh ~ ., data = landuse)
summary(m)

car::vif(lm(hh ~ ., data = landuse))
```

