---
title: "z-how-many-species-left-if-coverage-good"
output: html_document
---

```{r setup, include=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
# Global chunk options
if(!require("pacman")) install.packages("pacman")
p_load(readxl, tidyverse, cowplot, Hmsc, cli, knitr, sf)
opts_chunk$set(
	fig.align = "center",
	fig.height = 7,
	fig.width = 12,
	include = TRUE,
	echo = FALSE,
	warning = FALSE, 
	message = FALSE
)
```

```{r data}
# -----------------------------------------------------------------------------
# 1. LOAD DATA ONCE
# -----------------------------------------------------------------------------
input <- '.'

#### OCEAN THRESHOLD ####
grids_thresholds <- st_read(file.path(input, 'Data/data/1_preprocessing/atlas-grids/grids-ocean-thresholds/grids_ocean_thresholds.shp'))
thresholds <- grids_thresholds$kvdrtkd[grids_thresholds$pct_lnd >= 25]

#### EFFORT ####
get_effort <- function(dir){
  atlas1 <- read_excel(file.path(dir, 'effort', 'dækning atlas1+2.xlsx'), sheet = 'kvadrater atlas1')
  atlas2 <- read_excel(file.path(dir, 'effort', 'dækning atlas1+2.xlsx'), sheet = 'kvadrater atlas2')
  
  atlas2 <- atlas2 %>% 
    select(-UNDS_KODE_) %>% 
    rename(UNDS_KODE_ = UNDS_KOD_1)
  
  # Load design (Note: 'design' object is overwritten here in original code)
  load('HmscOutputs/2026-02-10_07-03-53_All_All_Atlas3_MinOccs5/Models/Fitted/HPC_samples_0250_thin_100_chains_4.Rdata')
  design <- read.csv('Data/data/1_preprocessing/design/studyDesign.csv')
  xycoords <- design[design$atlas == 2, c('site', 'lat', 'lon')]
  
  key <- read_excel(file.path(dir, 'effort', 'dækning atlas1+2.xlsx'), sheet = 'dækning') %>% 
    mutate(coverage = case_when(
      UNDSKODE == 0 ~ 'Not understood',
      UNDSKODE == 1 ~ 'Good',
      UNDSKODE == 2 ~ 'Average',
      UNDSKODE == 3 ~ 'Bad'
    ))
  
  effort <- rbind(
    atlas1 %>% mutate(atlas = 1),
    atlas2 %>% mutate(atlas = 2)
  ) %>% 
    left_join(key %>% rename(UNDS_KODE_ = UNDSKODE), by = "UNDS_KODE_") %>% 
    rename(site = KVADRATKOD) %>% 
    left_join(xycoords, by = 'site')
  
  effort$coverage <- factor(effort$coverage, levels = c('Good','Average','Bad','Not understood'))
  return(effort)
}

dir <- './Data'
effort <- get_effort(dir) %>% 
  mutate(survey = paste(.$site, .$atlas, sep='_')) %>% 
  select(survey, coverage) %>% 
  rbind(., data.frame(
    survey = paste(thresholds, 3, sep='_'),
    coverage = 'Good'
  ))

#### ENVIRONMENT ####
lulc_lookup <- c("0"="ocean", "11"="urban", "22"="cropland", "33"="pasture", "44"="forest", "55"="grass_shrub", "66"="other", "77"="water")

X <- read.csv(file.path(input, 'Data/data/1_preprocessing/X_environmental/X_Environmental.csv'), row.names=1) %>%
  rename_with(
    .cols = matches("^LULC_"),
    .fn = function(col) {
      lulc_code <- stringr::str_extract(col, "\\d+")
      paste0("perc_", lulc_lookup[lulc_code])
    }
  ) %>%
  mutate(perc_fresh_saltwater = perc_water + perc_ocean) %>%
  select(-perc_other, -perc_ocean, -perc_water) %>%
  mutate(
    dominant = factor(names(select(., starts_with("perc_")))[max.col(select(., starts_with("perc_")), ties.method = "first")])
  ) %>%
  filter(sub("_[123]$", "", rownames(.)) %in% thresholds) %>%
  drop_na() %>%
  filter(rownames(.) %in% effort$survey[effort$coverage == 'Good'])

#### OCCURRENCES ####  
Y <- read.csv(file.path(input, "Data/data/1_preprocessing/Y_occurrences/Y_occurrences.csv"), row.names = 1) %>%
  filter(row.names(.) %in% row.names(X))

# Sync X back to Y
X <- X %>% filter(rownames(.) %in% rownames(Y))
```

```{r functions}
# -----------------------------------------------------------------------------
# 2. DEFINE FILTERING AND PLOTTING FUNCTIONS
# -----------------------------------------------------------------------------
Y_matrix <- Y
plot_title <- 'test'
generate_coverage_report <- function(Y_matrix, filter_type = "each", min_occs = 5, plot_title) {
  
  # 1. Prepare data
  Y_long <- Y_matrix %>%
    as.data.frame() %>%
    rownames_to_column("site") %>%
    mutate(atlas = str_extract(site, "(?<=_)\\d$")) %>% 
    pivot_longer(-c(site, atlas), names_to = "species", values_to = "occ")
  
  # 2. Filter logic based on type ("each" vs "total")
  if (filter_type == "each") {
    to_remove <- Y_long %>%
      group_by(atlas, species) %>%
      summarise(n = sum(occ, na.rm = TRUE), .groups = "drop") %>%
      filter(n < min_occs) %>%
      pull(species) %>%
      unique()
  } else if (filter_type == "total") {
    to_remove <- Y_long %>%
      group_by(species) %>%
      summarise(total_occ = sum(occ, na.rm = TRUE), .groups = "drop") %>%
      filter(total_occ < min_occs) %>%
      pull(species)
  }
  
  # Subset matrix
  Y_sub <- Y_matrix[, !(colnames(Y_matrix) %in% to_remove), drop = FALSE]
  n_species <- ncol(Y_sub)
  
  # 3. Format for plotting
  df <- as.data.frame(Y_sub) %>%
    rownames_to_column("site") %>%
    mutate(atlas = str_extract(site, "_\\d$") |> str_remove("_"))
  
  occ_long <- df %>%
    pivot_longer(cols = -c(site, atlas), names_to = "species", values_to = "occ") %>%
    group_by(atlas, species) %>%
    summarise(total_occ = sum(occ, na.rm = TRUE), .groups = "drop")
  
  # Occurrences
  p_occ <- ggplot(occ_long, aes(x = atlas, y = total_occ, fill = atlas)) +
    geom_violin(trim = T,) +
    geom_jitter(width = 0.08, size = 1.3, alpha = 0.5) +
    stat_summary(fun = median, geom = "point", size = 2.5, colour = "black") +
    labs(x = "Atlas", y = "Occurrences / Species") +
    coord_cartesian(ylim = c(0,2000)) +
    theme_minimal(base_size = 13) +
    theme(
      legend.position = "none",
      plot.margin = margin(t = 2) # Reduce top margin to snap plots together
    )
  
  # Full Title
  title <- ggdraw() + 
    draw_label(paste0(plot_title, ": ", n_species, " species retained"), fontface = "bold", size = 16, x = 0, hjust = 0)
  
  # Combine with cowplot
  final_plot <- plot_grid(title, p_occ, ncol = 1, rel_heights = c(0.1, 1))
  
  return(final_plot)
}
```

# Only sites with good coverage 
- only good coverage
- assuming atlas 3 only has good coverage throughout

```{r}
generate_coverage_report(
  Y_matrix = Y, 
  filter_type = "each", 
  min_occs = 5, 
  plot_title = "Each species > 5 occurrences in each atlas"
)
```

```{r}
generate_coverage_report(
  Y_matrix = Y, 
  filter_type = "total", 
  min_occs = 5, 
  plot_title = "Each species > 5 occurrences in total across atlases"
)
```

```{r}
generate_coverage_report(
  Y_matrix = Y, 
  filter_type = "total", 
  min_occs = 20, 
  plot_title = "Each species > 20 occurrences in each atlas"
)
```


# All sites
- all coverage

```{r data-allcoverage, include = T ,echo = F}
# -----------------------------------------------------------------------------
# 1. LOAD DATA ONCE
# -----------------------------------------------------------------------------
input <- '.'

#### OCEAN THRESHOLD ####
grids_thresholds <- st_read(file.path(input, 'Data/data/1_preprocessing/atlas-grids/grids-ocean-thresholds/grids_ocean_thresholds.shp'))
thresholds <- grids_thresholds$kvdrtkd[grids_thresholds$pct_lnd >= 25]

#### ENVIRONMENT ####
lulc_lookup <- c("0"="ocean", "11"="urban", "22"="cropland", "33"="pasture", "44"="forest", "55"="grass_shrub", "66"="other", "77"="water")

X <- read.csv(file.path(input, 'Data/data/1_preprocessing/X_environmental/X_Environmental.csv'), row.names=1) %>%
  rename_with(
    .cols = matches("^LULC_"),
    .fn = function(col) {
      lulc_code <- stringr::str_extract(col, "\\d+")
      paste0("perc_", lulc_lookup[lulc_code])
    }
  ) %>%
  mutate(perc_fresh_saltwater = perc_water + perc_ocean) %>%
  select(-perc_other, -perc_ocean, -perc_water) %>%
  mutate(
    dominant = factor(names(select(., starts_with("perc_")))[max.col(select(., starts_with("perc_")), ties.method = "first")])
  ) %>%
  filter(sub("_[123]$", "", rownames(.)) %in% thresholds) %>%
  drop_na()

#### OCCURRENCES ####  
Y <- read.csv(file.path(input, "Data/data/1_preprocessing/Y_occurrences/Y_occurrences.csv"), row.names = 1) %>%
  filter(row.names(.) %in% row.names(X))

# Sync X back to Y
X <- X %>% filter(rownames(.) %in% rownames(Y))
```


```{r}
generate_coverage_report(
  Y_matrix = Y, 
  filter_type = "each", 
  min_occs = 5, 
  plot_title = "Each species > 5 occurrences in each atlas"
)
```

```{r}
generate_coverage_report(
  Y_matrix = Y, 
  filter_type = "total", 
  min_occs = 5, 
  plot_title = "Each species > 5 occurrences in total across atlases"
)
```

```{r}
generate_coverage_report(
  Y_matrix = Y, 
  filter_type = "total", 
  min_occs = 20, 
  plot_title = "Each species > 20 occurrences in each atlas"
)
```


