---
title: "z-visualising-effort"
output: html_document
---

```{r setup, include=TRUE,echo=FALSE}
# Global chunk options
knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "center",
	fig.height = 5,
	fig.width = 10,
	message = FALSE,
	warning = FALSE
)
if(!require("pacman")) install.packages("pacman")
pacman::p_load(readxl, tidyverse, sf, rnaturalearth)

```

```{r load-effort,include=TRUE}
dir <- './Data'
get_effort <- function(dir){
  # get seperate atlases 
  atlas1 <- read_excel(file.path(dir,'effort','dækning atlas1+2.xlsx'),
                       sheet = 'kvadrater atlas1')
  atlas2 <- read_excel(file.path(dir,'effort','dækning atlas1+2.xlsx'),
                       sheet = 'kvadrater atlas2')
  
  # check info 
  # hist(atlas1$UNDS_KODE_)
  # hist(atlas2$UNDS_KODE_)
  # hist(atlas2$UNDS_KOD_1)
  
  # UNDS_KOD_1 contains the info from atlas 1 and can be dropped 
  atlas2 <- atlas2 %>% 
    select(-UNDS_KODE_) %>% 
    rename(UNDS_KODE_=UNDS_KOD_1)
  
    # get xycoords 
  design <- load('HmscOutputs/2026-02-10_07-03-53_All_All_Atlas3_MinOccs5/Models/Fitted/HPC_samples_0250_thin_100_chains_4.Rdata')
  design <- read.csv('Data/data/1_preprocessing/design/studyDesign.csv')
  xycoords <- design[design$atlas==2,c('site','lat','lon')]
  
  # get key 
  key <- read_excel(file.path(dir,'effort','dækning atlas1+2.xlsx'),
                       sheet = 'dækning') %>% 
    ## let's immediately translate 
  mutate(coverage = case_when(
    UNDSKODE == 0 ~ 'Not understood',
    UNDSKODE == 1 ~ 'Good',
    UNDSKODE == 2 ~ 'Average',
    UNDSKODE == 3 ~ 'Bad'
  ))
  
  effort <- rbind(atlas1 %>% ### ADD ATLAS COLUMNS
          mutate(atlas = 1),
        atlas2 %>% 
          mutate(atlas = 2)) %>% ### JOIN WITH CODES
    left_join(
      key %>% rename(UNDS_KODE_ = UNDSKODE),
      by = "UNDS_KODE_"
    ) %>% ### ADD XY COORDS 
    rename(site = KVADRATKOD) %>% 
    left_join(
      xycoords,
      by = 'site'
    )
  effort$coverage <- factor(effort$coverage,
                               levels = c('Good','Average','Bad','Not understood'))
  return(effort)
}

### GET DATA / SET PLOTTING 
effort <- get_effort(dir)

base_colors <- c(
    "Good"     = "cadetblue3",
    "Average"   = "darkgreen",
    "Bad"   = "firebrick3",
    "Not understood" = "white"
)
  
denmark <- ne_countries(scale = "medium", country = "denmark", returnclass = "sf")

effort <- na.omit(effort)
lapply(c(1, 2), function(atlasnr) {

  pts_sf <- effort %>%
    filter(atlas == atlasnr) %>%
    st_as_sf(coords = c("lon", "lat"), crs = 4326, remove = FALSE) %>%  # data are lon/lat
    st_transform(23032)  # project to UTM32 / ED50

  p <- ggplot(denmark) +
    #geom_sf(fill = "grey95", color = "#333333", linewidth = 0.3) +
    geom_sf(data = pts_sf, aes(color = coverage), size = 1.2) +
    coord_sf(crs = st_crs(23032)) +
    scale_color_manual(values = base_colors) +
    theme_minimal() +
    ggtitle(sprintf("Atlas %s", atlasnr))
  print(p)
})

```
